this.models().getBuilder("blockbench_export").texture("2", 
	new ResourceLocation("FocusTable_BlockBench:focus_table_other.png"))
		.element().from(0F, 0F, 0F).to(16F, 4F, 16F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end().face(Direction.NORTH).uvs(0F, 0F, 16F, 4F).texture("#2").end()
			.face(Direction.EAST).uvs(0F, 0F, 16F, 4F).texture("#2").end()
			.face(Direction.SOUTH).uvs(0F, 0F, 16F, 4F).texture("#2").end()
			.face(Direction.WEST).uvs(0F, 0F, 16F, 4F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 16F, 16F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 16F, 16F).texture("#2").end().end()
		.element().from(1F, 4F, 4F).to(15F, 14F, 15F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end()
			.face(Direction.NORTH).uvs(0F, 2F, 14F, 12F).texture("#2").end()
			.face(Direction.EAST).uvs(0F, 2F, 11F, 12F).texture("#2").end()
			.face(Direction.SOUTH).uvs(0F, 2F, 14F, 12F).texture("#2").end()
			.face(Direction.WEST).uvs(0F, 2F, 11F, 12F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 14F, 11F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 14F, 11F).end().end()
		.element().from(7F, 4F, 1F).to(9F, 7F, 2F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end()
			.face(Direction.NORTH).uvs(5F, 9F, 7F, 12F).texture("#2").end()
			.face(Direction.EAST).uvs(6F, 9F, 7F, 12F).texture("#2").end()
			.face(Direction.SOUTH).uvs(2F, 1F, 4F, 4F).texture("#2").end()
			.face(Direction.WEST).uvs(1F, 1F, 2F, 4F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 2F, 1F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 2F, 1F).end().end()
		.element().from(6F, 7F, 1F).to(7F, 8F, 2F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end()
			.face(Direction.NORTH).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.EAST).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.SOUTH).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.WEST).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 1F, 1F).texture("#2").end().end()
		.element().from(9F, 7F, 1F).to(10F, 8F, 2F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end()
			.face(Direction.NORTH).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.EAST).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.SOUTH).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.WEST).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 1F, 1F).texture("#2").end().end()
		.element().from(5F, 8F, 1F).to(6F, 10F, 2F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end()
			.face(Direction.NORTH).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.EAST).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.SOUTH).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.WEST).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 1F, 1F).texture("#2").end().end()
		.element().from(10F, 8F, 1F).to(11F, 10F, 2F).rotation().angle(0F).axis(Axis.Y).origin(8F, 8F, 8F).end()
			.face(Direction.NORTH).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.EAST).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.SOUTH).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.WEST).uvs(0F, 0F, 1F, 2F).texture("#2").end()
			.face(Direction.UP).uvs(0F, 0F, 1F, 1F).texture("#2").end()
			.face(Direction.DOWN).uvs(0F, 0F, 1F, 1F).texture("#2").end().end()
		.transform(Perspective.THIRD_PERSON_RIGHT_HAND).scale(0.5F, 0.5F, -0.5F).end()
		.transform(Perspective.THIRD_PERSON_LEFT_HAND).scale(0.5F, 0.5F, -0.5F).end()
		.transform(Perspective.FIRST_PERSON_RIGHT_HAND).scale(0.5F, 0.5F, -0.5F).end()
		.transform(Perspective.FIRST_PERSON_LEFT_HAND).scale(0.5F, 0.5F, -0.5F).end()
		.transform(Perspective.GROUND).scale(0.5F, 0.5F, 0.5F).end()
		.transform(Perspective.GUI).rotation(23F, 133F, 0F).scale(0.75F, 0.75F, 0.75F).end()
		.transform(Perspective.HEAD).translation(0F, 12F, 0F).end()
		.transform(Perspective.FIXED).scale(0.5F, 0.5F, 0.5F).end()